/**
 * Configuration interface for the Layr extension
 */
export interface LayrConfig {
  geminiApiKey?: string;
}

/**
 * Represents a project plan generated by the AI or rule-based system
 */
export interface ProjectPlan {
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
  generatedAt: Date;
  generatedBy: 'ai' | 'rules';
}

/**
 * Represents a file or directory in the project structure
 */
export interface FileStructureItem {
  name: string;
  type: 'file' | 'directory';
  path: string;
  description?: string;
  children?: FileStructureItem[];
}

/**
 * Represents a step in the project plan
 */
export interface PlanStep {
  id: string;
  description: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  estimatedTime?: string;
  dependencies?: string[];
}

/**
 * Interface for plan generators (AI or rule-based)
 */
export interface PlanGenerator {
  generatePlan(prompt: string): Promise<ProjectPlan>;
  isAvailable(): Promise<boolean>;
}

/**
 * Template for rule-based plan generation
 */
export interface PlanTemplate {
  keywords: string[];
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
}

/**
 * Error types for plan generation
 */
export class PlanGenerationError extends Error {
  constructor(message: string, public cause?: Error) {
    super(message);
    this.name = 'PlanGenerationError';
  }
}

export class APIKeyMissingError extends PlanGenerationError {
  constructor() {
    super('Gemini API key is missing. Please configure it in settings or .env file.');
    this.name = 'APIKeyMissingError';
  }
}

export class AIServiceError extends PlanGenerationError {
  constructor(message: string, cause?: Error) {
    super(`AI service error: ${message}`, cause);
    this.name = 'AIServiceError';
  }
}